# Translations template for PROJECT.
# Copyright (C) 2022 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-03-01 13:11+1000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.1.1\n"

#: oslo_vmware/api.py:322
#, python-format
msgid ""
"Current session: %(session)s is inactive; re-creating the session while "
"invoking method %(module)s.%(method)s."
msgstr ""

#: oslo_vmware/api.py:495
#, python-format
msgid "Lease: %(lease)s is in error state. Details: %(error_msg)s."
msgstr ""

#: oslo_vmware/api.py:502
#, python-format
msgid "Unknown state: %(state)s for lease: %(lease)s."
msgstr ""

#: oslo_vmware/exceptions.py:52
msgid "An unknown exception occurred."
msgstr ""

#: oslo_vmware/exceptions.py:62
msgid "exception message must not be a list"
msgstr ""

#: oslo_vmware/exceptions.py:65
msgid "details must be a dict"
msgstr ""

#: oslo_vmware/exceptions.py:140
msgid "fault_list must be a list"
msgstr ""

#: oslo_vmware/exceptions.py:173
msgid "VMware Driver configuration fault."
msgstr ""

#: oslo_vmware/exceptions.py:182
msgid "No default value for use_linked_clone found."
msgstr ""

#: oslo_vmware/exceptions.py:186
#, python-format
msgid "Missing parameter : %(param)s"
msgstr ""

#: oslo_vmware/exceptions.py:194
msgid "Resource already exists."
msgstr ""

#: oslo_vmware/exceptions.py:199
msgid "Cannot delete file."
msgstr ""

#: oslo_vmware/exceptions.py:204
msgid "File already exists."
msgstr ""

#: oslo_vmware/exceptions.py:209
msgid "File fault."
msgstr ""

#: oslo_vmware/exceptions.py:214
msgid "File locked."
msgstr ""

#: oslo_vmware/exceptions.py:219
msgid "File not found."
msgstr ""

#: oslo_vmware/exceptions.py:224
msgid "Invalid power state."
msgstr ""

#: oslo_vmware/exceptions.py:229
msgid "Invalid property."
msgstr ""

#: oslo_vmware/exceptions.py:234
msgid "No Permission."
msgstr ""

#: oslo_vmware/exceptions.py:239
msgid "Not Authenticated."
msgstr ""

#: oslo_vmware/exceptions.py:244
msgid "Entity has another operation in process."
msgstr ""

#: oslo_vmware/exceptions.py:248
msgid "Duplicate name."
msgstr ""

#: oslo_vmware/exceptions.py:252
msgid "Insufficient disk space."
msgstr ""

#: oslo_vmware/exceptions.py:256
msgid "VMware Tools is not running."
msgstr ""

#: oslo_vmware/exceptions.py:260
msgid "Managed object not found."
msgstr ""

#: oslo_vmware/exceptions.py:323
msgid "exception should be a subclass of VimException"
msgstr ""

#: oslo_vmware/image_transfer.py:63
#, python-format
msgid "Timeout, read_handle: \"%(src)s\", write_handle: \"%(dest)s\""
msgstr ""

#: oslo_vmware/image_transfer.py:69
#, python-format
msgid "Error, read_handle: \"%(src)s\", write_handle: \"%(dest)s\""
msgstr ""

#: oslo_vmware/image_transfer.py:253
#, python-format
msgid "No vmdk found in the OVA image %s."
msgstr ""

#: oslo_vmware/rw_handles.py:84 oslo_vmware/objects/datastore.py:433
#, python-format
msgid "Invalid scheme: %s."
msgstr ""

#: oslo_vmware/rw_handles.py:107
#, python-format
msgid "Error occurred while opening URL: %s for reading."
msgstr ""

#: oslo_vmware/rw_handles.py:142
#, python-format
msgid ""
"Error occurred while creating HTTP connection to write to VMDK file with "
"URL = %s."
msgstr ""

#: oslo_vmware/rw_handles.py:262 oslo_vmware/rw_handles.py:538
#, python-format
msgid "Connection error occurred while writing data to %s."
msgstr ""

#: oslo_vmware/rw_handles.py:270 oslo_vmware/rw_handles.py:546
#, python-format
msgid "Error occurred while writing data to %s."
msgstr ""

#: oslo_vmware/rw_handles.py:451
msgid "Could not retrieve VMDK URL from lease info."
msgstr ""

#: oslo_vmware/rw_handles.py:520
#, python-format
msgid "Incomplete VMDK upload to %s."
msgstr ""

#: oslo_vmware/rw_handles.py:624
#, python-format
msgid "Error occurred while reading data from %s."
msgstr ""

#: oslo_vmware/service.py:301
msgid "Error occurred while calling RetrievePropertiesEx."
msgstr ""

#: oslo_vmware/service.py:418
#, python-format
msgid "No such SOAP method %s."
msgstr ""

#: oslo_vmware/service.py:424
#, python-format
msgid "httplib error in %s."
msgstr ""

#: oslo_vmware/service.py:428
#, python-format
msgid "requests error in %s."
msgstr ""

#: oslo_vmware/service.py:439
#, python-format
msgid "Socket error in %s."
msgstr ""

#: oslo_vmware/service.py:444
#, python-format
msgid "Type error in %s."
msgstr ""

#: oslo_vmware/service.py:447
#, python-format
msgid "Exception in %s."
msgstr ""

#: oslo_vmware/objects/datacenter.py:23
msgid "Datacenter name cannot be None"
msgstr ""

#: oslo_vmware/objects/datacenter.py:25
msgid "Datacenter reference cannot be None"
msgstr ""

#: oslo_vmware/objects/datastore.py:168
msgid "Datastore name cannot be None"
msgstr ""

#: oslo_vmware/objects/datastore.py:170
msgid "Datastore reference cannot be None"
msgstr ""

#: oslo_vmware/objects/datastore.py:172
msgid "Invalid capacity"
msgstr ""

#: oslo_vmware/objects/datastore.py:175
msgid "Capacity is smaller than free space"
msgstr ""

#: oslo_vmware/objects/datastore.py:204
msgid "datacenter must be set to build url"
msgstr ""

#: oslo_vmware/objects/datastore.py:304
msgid "Datastore name cannot be empty"
msgstr ""

#: oslo_vmware/objects/datastore.py:309 oslo_vmware/objects/datastore.py:350
msgid "Path component cannot be None"
msgstr ""

#: oslo_vmware/objects/datastore.py:363
msgid "Datastore path cannot be empty"
msgstr ""

#: oslo_vmware/objects/datastore.py:446
#, python-format
msgid ""
"Error occurred while creating HTTP connection to write to file with URL ="
" %s."
msgstr ""

#: oslo_vmware/tests/test_exceptions.py:34
msgid "string"
msgstr ""

#: oslo_vmware/tests/test_exceptions.py:44
msgid "cause"
msgstr ""

